# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20160102_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='up_votes',
        ),
    ]
