# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20160102_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='down_votes',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='movie',
            name='up_votes',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
