# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20160102_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='review',
            field=models.TextField(),
        ),
    ]
