# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20160109_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='review',
            field=models.TextField(max_length=200),
        ),
    ]
