# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 01:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
