# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_publishedmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.CharField(default='', max_length=50),
        ),
    ]
