# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('year_published', models.CharField(max_length=250)),
                ('genres', models.CharField(max_length=100)),
            ],
        ),
    ]
